### ISSUE TITLE
Error when running install.sh after PiKVM OS update from October 2023

### ISSUE THREAD

**Issue by eeeeb** [zappanaut/dln2-dkms#2]
Hello, after running the bigger PiKVM update from October 2023 (see announcement: https://discord.com/channels/580094191938437144/712960053174599712/1165521850743410779) I ran into the issue the the PiKVM is throwing a 500 error in the webgui. Before that everything was working fine.
Usually when this happens this is tied to the connected [pikvm-usb-atx-ctrl](https://github.com/zappanaut/pikvm-usb-atx-ctrl) not being detected and showing up in the directory /dev/gpio-by-serial. So I checked that and noticed that the directory gpio-by-serial was empty. 

So I thought perhaps after the OS update, I need to install [dln2-dkms](https://github.com/zappanaut/dln2-dkms) again.
I followed the instructions again:
`git clone https://github.com/zappanaut/dln2-dkms
pacman -S dkms
cd dln2-dkms
./install.sh
reboot`

But when running the install.sh, I get the following error message (the initial message might have been different, as I ran it twice now). But I assume the issue is the last section of the error message.

./install.sh
mkdir: cannot create directory '/dev/gpio-by-serial': File exists
Error! DKMS tree already contains: dln2-5.15.0
You cannot add the same module/version combo more than once.
The kernel is be built without module signing facility, modules won't be signed
Error! The /var/lib/dkms/dln2/5.15.0/6.1.61-1-rpi-ARCH/armv7l/dkms.conf for module dln2 includes a BUILD_EXCLUSIVE directive which does not match this kernel/arch/config.
This indicates that it should not be built.
The kernel is be built without module signing facility, modules won't be signed
Error! The /var/lib/dkms/dln2/5.15.0/6.1.61-1-rpi-ARCH/armv7l/dkms.conf for module dln2 includes a BUILD_EXCLUSIVE directive which does not match this kernel/arch/config.
This indicates that it should not be built.``

I rebooted the PIKVM several times, but the USB devices will not show up in the directory gpio-by-serial.
So I am not sure if this issue is related to dln2-dkms, but I thought I start here to find out if this error might be the cause.

**Comment by zappanaut** [comment]
Hello! I updated the code to be compatible with the most recent pikvm version. Please pull again and give that one a try.

**Comment by eeeeb** [comment]
Thank you very much for the quick fix!
Works perfectly again.
